### ISSUE TITLE
Not compatible with astro 2.1

### ISSUE THREAD

**Issue by ngmisl** [lancerossdev/nofuss#6]

**Comment by lancerossdev** [comment]
Hey there,

Sorry, but I don't have time to update my projects to Astro v2 anymore, including this nofuss. I don't do web development stuff anymore and I think I will abandon this project for now. It would be nice if someone will have a "successor" of this template because people seem to like it (idk why lol). That's all I can answer for now and thank you for understanding.

Regards,
Lance :)
